FROM openjdk:11-jre-slim
COPY ./build/libs/*.jar app.jar
ARG DB_URL
ARG DB_USER
ARG DB_PWD
ARG JWT_SECRET
ARG FIREBASE_URL
ARG FIREBASE_FILE
ARG SMS_API_KEY
ARG SMS_SECRET_KEY
ARG SMS_FROM_PHONE_NUMBER

ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PWD}
ENV JWT_SECRET=${JWT_SECRET}
ENV FIREBASE_URL=${FIREBASE_URL}
ENV FIREBASE_FILE=${FIREBASE_FILE}
ENV SMS_API_KEY=${SMS_API_KEY}
ENV SMS_SECRET_KEY=${SMS_SECRET_KEY}
ENV SMS_FROM_PHONE_NUMBER=${SMS_FROM_PHONE_NUMBER}

ENTRYPOINT ["java","-jar","-Dspring.datasource.url=${DB_URL}","-Dspring.datasource.username=${DB_USER}", "-Dspring.jwt.secret-key=${JWT_SECRET}", "-Dspring.datasource.password=${DB_PASSWORD}",  "-Dspring.sms.apikey=${SMS_API_KEY}", "-Dspring.sms.secret=${SMS_SECRET_KEY}", "-Dspring.sms.phoneNumber=${SMS_FROM_PHONE_NUMBER}", "/app.jar"]
