spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB


jwt:
  secret-key: ${JWT_SECRET:qwer1234}
  access-exp: ${JWT_ACCESS_EXP:12345}
  refresh-exp: ${JWT_REFRESH_EXP:3456789}

aws:
  ses:
    access-key: ${AWS_SES_ACCESS}
    secret-key: ${AWS_SES_SECRET}
    region: ${AWS_SES_REGION}
    email: ${SENDER_EMAIL}

