server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcs
    username: root
    password: epdlxjqpdltmqlalfqjsgh!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB


jwt:
  secret-key: ${JWT_SECRET:qwer1234}
  access-exp: ${JWT_ACCESS_EXP:12345}
  refresh-exp: ${JWT_REFRESH_EXP:3456789}
